name: sprite_frames
description: A starting point for Dart libraries or applications.
version: 0.0.4
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'
  
dependencies:
  flutter:
    sdk: flutter 
  flame: 
    path: ../../flutter_works/flame
  crypto:
  pvr_ccz:
    version: ^0.0.3
    path: ../pvr-ccz
    # git:
    #   url: git://github.com/bung87/pvr-ccz.git

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
